//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agenda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class appointments
    {
        public int id { get; set; }

        [DisplayName("Date et heure")]
        [Required]
        public System.DateTime dateHour { get; set; }

        [DisplayName("Sujet")]
        [Required]
        public string subject { get; set; }

        [DisplayName("Courtier concerné")]
        [Required]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Selection non valide")]
        public int id_brokers { get; set; }

        [DisplayName("Client concerné")]
        [Required]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Selection non valide")]
        public int id_customers { get; set; }

        //Attribut date de type string qui stock que la date de l'attribut dateHour en format complet (Ex: lundi 13 Octobre 1997)
        public string date {
            get
            {
                return dateHour.ToLongDateString();
            }
         }

        //Attribut hour de type string qui stock que l'heure de l'attribut dateHour convertit en string
        public string hour
        {
            get
            {
                return dateHour.Hour.ToString();
            }
        }
        public virtual brokers brokers { get; set; }
        public virtual customers customers { get; set; }
    }
}
